
pool:
  vmImage: 'windows-2019'

variables:
  artifactsFeedId: '/36e50407-5798-43e2-b0e2-a0de0e3f46c6'

steps:
- task: GitVersion@4
  displayName: Git Version
  inputs:
    updateAssemblyInfo: false

- task: DotNetCoreCLI@2
  displayName: Restore NuGet Packages
  inputs:
    command: 'restore'
    projects: '**/*.sln'
    feedsToUse: 'select'
    vstsFeed: $(artifactsFeedId)

- task: DotNetCoreCLI@2
  displayName: Build Projects
  inputs:
    command: build
    projects: '**/*.sln'
    arguments: --no-restore

- task: PowerShell@2
  displayName: Update TemplateVersion props
  inputs:
    filePath: 'build/Update-TemplateVersions.ps1'


- task: NuGetCommand@2
  displayName: NuGet Pack
  inputs:
    command: pack
    packagesToPack: src/NV.Templates.nuspec
    packDestination: $(build.artifactStagingDirectory)
    versioningScheme: byEnvVar
    versionEnvVar: GitVersion.NuGetVersionV2

- task: PublishBuildArtifacts@1
  displayName: 'Publish Build Artifacts'

- task: NuGetCommand@2
  inputs:
    command: 'push'
    packagesToPush: '$(build.artifactStagingDirectory)/**/*.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: '$(artifactsFeedId)'
  condition: and(succeeded(), or(eq(variables['Build.SourceBranch'], 'refs/heads/master'), eq('true', variables['forcePushNuget'])))
